# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='freeboard',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='question',
        ),
        migrations.RemoveField(
            model_name='review',
            name='question',
        ),
        migrations.DeleteModel(
            name='Thanks',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FreeBoard',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
